In [17]:
'''This cell imports pandas and the CSV file contiang the data that needs to be sorted and stores it as 'ctf' 

Genral note: This note book was created as a simplified verion of the filter interface notebook and carried over variable names from that project '''

import pandas as pd
import csv
import numpy as np
from astropy import units as u
from astropy.coordinates import Angle



pd.set_option("display.max_rows", None, "display.max_columns", None)

TUI_Targets=pd.read_csv('GeminiTargetsTake1.csv')

display(TUI_Targets)
        
#print ("\nImport Complete\n")

                        Name          RA        Dec        Class       Gmag
0   WISE J045451.56-670203.9   73.714861 -67.034497           EM  14.046777
1   WISE J045550.56-695807.0   73.960641 -69.968616           EM  13.954285
2   WISE J045719.13-673047.0   74.329243 -67.513090           EM  14.631564
3   WISE J050128.62-701120.2   75.369061 -70.188978           EM  13.878529
4   WISE J051038.76-642117.8   77.661495 -64.354943           EM  14.231917
5   WISE J051852.07-625750.2   79.716991 -62.963962  Contaminant  14.807224
6   WISE J052915.30-671259.8   82.313739 -67.216612           EM  13.706032
7   WISE J053001.84-664614.4   82.507758 -66.770707           EM  13.860653
8   WISE J053323.01-673059.8   83.345961 -67.516699           EM  13.637502
9   WISE J053424.65-662557.5   83.602704 -66.432664           EM  13.660733
10   2MASS J05362506-7012222   84.104532 -70.206180           EM  16.012371
11  WISE J110247.58-610632.9  165.698217 -61.109151           EM  11.111307
12              CPD-60  2585  167.555988 -60.775415           EM   9.750662

In [18]:
def TUI_Convertor(TUI_Targets):
    def Convert_To_DMS(valueOfDec):
        valueOfDec=Angle(valueOfDec, u.degree)
        valueOfDec=valueOfDec.to_string(unit=u.degree,sep=':')
        return valueOfDec

    def Convert_To_HMS(valueOfRA):
        valueOfRA=Angle(valueOfRA, u.degree)
        valueOfRA=valueOfRA.to_string(unit=u.hour, sep=':')
        return valueOfRA

    def MagEquals(GmagVal):
        str(GmagVal)
        GmagVal="Magnitude="+GmagVal.apply(str)
        return GmagVal



    def NameEquals(starName):

        starName='"'+starName+'"'
        return starName






    TUI_Targets2=TUI_Targets

    TUI_Targets2.Dec = Convert_To_DMS(TUI_Targets.Dec)



    TUI_Targets3=TUI_Targets2

    TUI_Targets3.RA = Convert_To_HMS(TUI_Targets.RA)


    TUI_Targets4=TUI_Targets3
    TUI_Targets3.Gmag = MagEquals(TUI_Targets3.Gmag)
    TUI_Targets4.Name = NameEquals(TUI_Targets3.Name)


    TUI_Targets5 = TUI_Targets4.drop(columns=['Class'])
    TUI_TargetsFinal = TUI_Targets5.rename(columns={'Name':'#Name'},index={'One':'Row_1'})


    TUI_TargetsFinal.to_csv('GeminiTargetsTUI_V1.csv',index = False, na_rep="NAN!",sep='\t', quoting=csv.QUOTE_NONE)

    TUI_TargetsFinal.to_csv('GeminiTargetsTUI_V1_NO_TABS.csv',index = False, na_rep="NAN!")

    display(TUI_TargetsFinal)

In [19]:
TUI_Convertor(TUI_Targets)

,#Name,RA,Dec,Gmag
0,"""WISE J045451.56-670203.9""",4:54:51.5666,-67:02:04.1902,Magnitude=14.046777
1,"""WISE J045550.56-695807.0""",4:55:50.5539,-69:58:07.0171,Magnitude=13.954285
2,"""WISE J045719.13-673047.0""",4:57:19.0183,-67:30:47.1236,Magnitude=14.631564
3,"""WISE J050128.62-701120.2""",5:01:28.5746,-70:11:20.3207,Magnitude=13.878529
4,"""WISE J051038.76-642117.8""",5:10:38.7587,-64:21:17.7959,Magnitude=14.231917
5,"""WISE J051852.07-625750.2""",5:18:52.0778,-62:57:50.2623,Magnitude=14.807224
6,"""WISE J052915.30-671259.8""",5:29:15.2975,-67:12:59.8042,Magnitude=13.706032
7,"""WISE J053001.84-664614.4""",5:30:01.8619,-66:46:14.5453,Magnitude=13.860653
8,"""WISE J053323.01-673059.8""",5:33:23.0307,-67:31:00.1152,Magnitude=13.637502
9,"""WISE J053424.65-662557.5""",5:34:24.6489,-66:25:57.589,Magnitude=13.660733
10,"""2MASS J05362506-7012222""",5:36:25.0876,-70:12:22.2496,Magnitude=16.012370999999998
11,"""WISE J110247.58-610632.9""",11:02:47.572,-61:06:32.9421,Magnitude=11.111307
12,"""CPD-60 2585""",11:10:13.4371,-60:46:31.4945,Magnitude=9.750662

In [20]:
# tsi = pd.read_csv ('V3COSMOS_Targets_Converted_No_Class_Adjsuted_Mag_Tab_Seperated.csv')
# tsi
# tsi2 = pd.read_csv ('csvFormatCOSMOS_Targets_Converted_No_Class_Adjsuted_Mag.csv')
# tsi2
#tsi.to_csv('TabSep_COSMOS_Targets_Converted3.csv',index = False, na_rep="NAN!",sep='\t')